name: CI
on:
  push: {}
  pull_request: {}
  workflow_dispatch: {}

jobs:
  oidc:
    runs-on: depot-ubuntu-22.04-arm
    permissions:
      contents: read
      id-token: write
    steps:
      - run: env
      - run: cat $GITHUB_EVENT_PATH | jq .
